openapi: 3.0.2
info:
  title: Blog Aggregator Rest API
  version: 0.1.0
  description: REST API for interacting with the Blog Aggregator
components:
  schemas:
    AddBlogRequest:
      type: object
      properties:
        url:
          type: string
    SuccessResponse:
      type: object
      properties:
        message:
          type: string
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
        code:
          type: string
x-weos-config:
  logger:
    level: warn
  database:
    database: test.db
    driver: sqlite3
paths:
  /:
    get:
      operationId: Homepage
      responses:
        200:
          description: Application Homepage
  /blog:
    put: 
      operationId: Add Blog
      x-weos-config:
        handler: AddBlog
      requestBody:
        description: Blog info that is submitted
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AddBlogRequest"
      responses:
        201:
          description: Add Blog to Aggregator
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResponse"
        400:
          description: Invalid blog submitted
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

